# Generated by Django 4.0.3 on 2022-03-20 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_alter_login_email_alter_login_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_name',
            name='id_key',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='login',
            name='last_login',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 20, 8, 31, 29, 958508)),
        ),
    ]
