# Generated by Django 3.2.6 on 2022-03-19 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uplaodingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentNumber', models.BigIntegerField()),
                ('DocumentType', models.CharField(max_length=200)),
                ('itemType', models.CharField(max_length=200)),
                ('documentDate', models.DateField(default=datetime.datetime.today)),
                ('documentFile', models.FileField(upload_to='static')),
            ],
        ),
    ]
