# Generated by Django 3.2.6 on 2022-03-19 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newFCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 3, 19, 15, 2, 25, 799980))),
                ('FCompany', models.CharField(max_length=200)),
                ('depostieAmount', models.IntegerField()),
                ('paymenetAmount', models.IntegerField()),
                ('DepPAyDate', models.DateField()),
                ('netAmount', models.IntegerField()),
            ],
        ),
    ]
