# Generated by Django 3.2.6 on 2022-03-19 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_newfcompany_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='advanceFcompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('idComapny', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('recevingNumber', models.BigIntegerField()),
                ('receivingAmount', models.BigIntegerField()),
                ('expenceNumber', models.BigIntegerField()),
                ('expenceAmount', models.BigIntegerField()),
                ('depositeAmount', models.BigIntegerField()),
                ('paymentAmount', models.BigIntegerField()),
                ('DepPayDate', models.DateField()),
                ('FCompany', models.CharField(max_length=200)),
                ('RecLink', models.URLField()),
                ('NetAmount', models.BigIntegerField()),
                ('receiDepPay', models.BigIntegerField()),
                ('details', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
